#
# Copyright Motorola Solutions, Inc. and/or Kodiak Networks, Inc.                                 
# All Rights Reserved                                                                             
# Motorola Solutions Confidential Restricted                                                      
#
batch.jdbc.driver=com.timesten.jdbc.TimesTenDriver
batch.jdbc.url=
batch.jdbc.user=
batch.jdbc.password=
batch.jdbc.testWhileIdle=true
batch.jdbc.validationQuery=SELECT EMSCARDID from DG.EMSINFO;
batch.jdbc.verifyCursorPosition=true
batch.data.source.init=true
batch.jdbc.pool.size=6
batch.verify.cursor.position=true
batch.database.incrementer.class=org.springframework.jdbc.support.incrementer.MySQLMaxValueIncrementer
batch.database.incrementer.parent=columnIncrementerParent
batch.lob.handler.class=org.springframework.jdbc.support.lob.DefaultLobHandler
batch.grid.size=50
batch.drop.script=classpath:schema-drop-timesten.sql
batch.schema.script=classpath:schema-timesten.sql