#
# Copyright Motorola Solutions, Inc. and/or Kodiak Networks, Inc.                                 
# All Rights Reserved                                                                             
# Motorola Solutions Confidential Restricted                                                      
#
# Will be used by [WEB or XDM] card for local logging
log4j.appender.log=org.apache.log4j.RollingFileAppender
log4j.appender.log.File=
log4j.appender.log.MaxFileSize=
log4j.appender.log.MaxBackupIndex=
log4j.appender.log.immediateFlush=true
log4j.appender.log.bufferedIO=false
log4j.appender.log.layout=org.apache.log4j.TTCCLayout
log4j.appender.log.layout.ContextPrinting=true
log4j.appender.log.layout.DateFormat=ISO8601

# Will be used by [WEB or XDM] card for remote logging
log4j.appender.syslog=org.apache.log4j.net.SyslogAppender
log4j.appender.syslog.SyslogHost=
log4j.appender.syslog.Facility=
log4j.appender.syslog.Header=true
log4j.appender.syslog.layout=org.apache.log4j.TTCCLayout
log4j.appender.syslog.layout.ContextPrinting=true
