#
# Copyright Motorola Solutions, Inc. and/or Kodiak Networks, Inc.                                 
# All Rights Reserved                                                                             
# Motorola Solutions Confidential Restricted                                                      
#
#
# File Name : log4j-config.properties
# Libraries log initialization file
#
Log4jPropsFile=@web-activerelease.path@/@wpslog.name@
WatchDelay=600000
